### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by mrmlnc** [remarkjs/vscode-remark#22]
Hello, friends,

Sadly, I don't have a lot of time to support this plugin (and some others). Although I wish it development. Reply to this issue if you find yourself interested in owning this plugin.

I will transfer the repository and publishing rights to VS Code store (I don't know how to do it yet, [click](https://github.com/microsoft/vscode/issues/21478)).

**Comment by mrmlnc** [comment]
Maybe you want to think it over...

//cc @asbjornu @tengattack

**Comment by asbjornu** [comment]
Sad, but understandable. I think we should approach [remarkjs](https://github.com/remarkjs/) and have the repository transferred to them. Do you want me to initiate that dialogue?

**Comment by mrmlnc** [comment]
Yeap, if you have a desire :)

**Comment by asbjornu** [comment]
Done: remarkjs/remark#508.

**Comment by asbjornu** [comment]
My request has been answered (see https://github.com/remarkjs/remark/issues/508#issuecomment-652450604) and we are asked to follow [these guidelines](https://github.com/unifiedjs/collective/blob/main/organizations.md#motion-to-grant-governance). Can you please follow through with the things you need to do there, @mrmlnc?

**Comment by asbjornu** [comment]
@wooorm, can you please give me admin access so we can have this closed? 😃 🙏

**Comment by wooorm** [comment]
Is there anything important you can’t do to the repo with your current write/merge rights? For security reasons, we want to have a small group with admin access.

**Comment by asbjornu** [comment]
I would like to adjust the branch protection, configure Dependabot, configure merged branch deletion, etc.

**Comment by wooorm** [comment]
@asbjornu That sounds like something that can be done once. Can I do that for you?

**Comment by asbjornu** [comment]
Sorry for being blunt, but I reckon it's better to be honest and frank about this than not. I don't think I'm going to be enjoying maintaining this repository without administrative access. I did not anticipate having to ask someone else for permission to increase the quality of this project when I volunteered to maintain it.

Let's take branch protection as an example. I'd like to set it up to require pull request reviews and checks. Each check is named and if I decide to rename a check in the `.yml` file, I would have to ask you to change which check is required. If I add checks, I would have to ask you to make them required. If I would like to add a social image to the repository, I would have to ask you. If I want to add Codacy or other external tools to analyze the code, I would have to ask you. Perhaps that's OK with you, but I'm sorry, it isn't for me.

**Comment by wooorm** [comment]
Whether projects make sense to be maintained in the unified collective is described in the document you’ve seen before. [At the top of our organizations policy](https://github.com/unifiedjs/collective/blob/main/organizations.md#projects).

> I did not anticipate having to ask someone else for permission to increase the quality of this project when I volunteered to maintain it.

That’s a misrepresentation of what this is about. It’s security, stability, longevity, community.

The rest of your comment is also a misrepresentation of what maintaining open source is. I feel open source is grunt work: triage and code. Not a lot of changing metadata. Furthermore, open source is collaborative. It’s not about you and me. [It’s about making decisions as a group](https://github.com/unifiedjs/collective/blob/main/decisions.md)

---

I’d like to remind you that you pushed for the unified collective to assume governance over the project while volunteering to maintain it. However, if you feel strongly impaired and Denis is okay with you maintaining this project on your own, see the [motion to withdraw governance](https://github.com/unifiedjs/collective/blob/main/organizations.md#motion-to-withdraw-governance)

**Comment by asbjornu** [comment]
> Whether projects make sense to be maintained in the unified collective is described in the document you’ve seen before. [At the top of our organizations policy](https://github.com/unifiedjs/collective/blob/main/organizations.md#projects).

I'm sorry for mistakenly thinking that being the maintainer of an open source project meant I could administer it.
 
> > I did not anticipate having to ask someone else for permission to increase the quality of this project when I volunteered to maintain it.
> 
> That’s a misrepresentation of what this is about. It’s security, stability, longevity, community.

Does making me comfortable as a maintainer of this repository go against security, stability, longevity or community? If your policies deter people like me from coming onboard and putting work in to maintain repositories, doesn't that achieve precisely the opposite of what your policy is created for?

> The rest of your comment is also a misrepresentation of what maintaining open source is. I feel open source is grunt work: triage and code. Not a lot of changing metadata. Furthermore, open source is collaborative. It’s not about you and me. [It’s about making decisions as a group](https://github.com/unifiedjs/collective/blob/main/decisions.md)

While in broad terms I agree, open source development comes down to singular human beings putting in their free time to do something they are usually not paid to do. I value my spare time a whole lot. If there's a lot of friction involved in the things I spend my free time on, the thing sure is going to either be very important to me; very fun; or both.

Since vscode-remark provides utility to me, I thought that my experience of maintaining other open source repositories would be helpful to allow this utility to continue to exist at least for as long as I'm using it.

> I’d like to remind you that you pushed for the unified collective to assume governance over the project while volunteering to maintain it.

Sorry I didn't read the fine print. If there's no way to budge on the policy, I will have to sit down, take screenshots and write up procedures for how you can adjust everything according to how I'd like things to be in order to maintain this repository. I hope to find time to do that later in the week.

> However, if you feel strongly impaired and Denis is okay with you maintaining this project on your own, see the [motion to withdraw governance](https://github.com/unifiedjs/collective/blob/main/organizations.md#motion-to-withdraw-governance)

While that is an option, I still think the project belongs in the remarkjs organization.

**Comment by wooorm** [comment]
> Does making me comfortable [..] doesn't that achieve precisely the opposite of what your policy is created for?

I hope that whether you can upload a social image directly, or raise an issue and have someone else do it, has no impact on whether your day is comfortable or not. But indeed, policies are not (**only**) created for maintainers to be comfortable.

> [...] open source development comes down to singular human beings [...]

This is also true for the other members of the remark organization and the rest of the unified collective.

> I thought that my experience of maintaining other open source repositories would be helpful

It is, your experience is valued.

> I will have to sit down, take screenshots and write up procedures for how you can adjust everything according to how I'd like things to be in order to maintain this repository.

I would suggest not thinking about branch protection for a days but instead to first try and work together and then see what can be better?

**Comment by asbjornu** [comment]
> I would suggest not thinking about branch protection for a days but instead to first try and work together and then see what can be better?

I don't plan to spend days **thinking** about branch protection, but instead of just clicking "Settings" in this repository and adjust them directly, I now have to go over to another repository, look at the UI, write down procedures for how I want it configured and possibly take screenshots. That takes time I don't have to allot at the moment.

**Comment by ChristianMurphy** [comment]
> If I want to add Codacy or other external tools to analyze the code

I've worked with Codacy and other similar tools before, they're a thin wrapper around ESLint.
ESLint is usually a better starting point because it can be run locally and on CI, as well as supporting more validations than other tooling.
Codacy can be added for a nice visual, but adding it first is putting the cart before the horse.

> I don't plan to spend days thinking about branch protection

@asbjornu chill.
unified/remark already does code reviews and ensures CI is passing before merging.
If you want required checks switched on, it can be done. It isn't a blocker to contributing.

**Comment by ChristianMurphy** [comment]
@asbjornu to help alleviate your concern.
the main branch is now protected.
It requires:
* 1 code review before merging
* the linux build to pass before merging
* the branch to up-to-date before merging
* commits to be signed

If you have other requests or concerns, feel free to open another issue (since this is off topic from "Maintainers wanted).
Or if it's something you see having broader adoption within Unified, open a discussion https://github.com/remarkjs/remark/discussions or RFC https://github.com/unifiedjs/rfcs
